# Generated by Django 5.2.6 on 2026-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('health', 'Health'), ('finance', 'Finance'), ('other', 'Other')], default='personal', max_length=20, verbose_name='Category'),
        ),
    ]
