name: Django CI/CD with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup and Build Infrastructure
      run: docker compose up -d --build

    - name: Wait for database to be ready
      run: sleep 10

    - name: Check running containers
      run: docker compose ps

    - name: Run Linter (Flake8)
      run: docker compose run --rm web flake8 . --extend-ignore=E501

    - name: Shutdown Infrastructure
      if: always()
      run: docker compose down -v